# Generated by Django 4.2 on 2023-10-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='job_count',
            field=models.IntegerField(verbose_name='Job Count'),
        ),
    ]
